---
nginx_port_no_tls: 80
nginx_port_tls: 443
server_hostname: "example1.com"
crt_controller_dir: "/etc/ssl/certs/{{ server_hostname }}"
crt_compute_dir: "/etc/ssl/certs/{{ server_hostname }}"
privatekey_filename: "private_key.pem"
csr_filename: "{{ server_hostname }}.csr"
crt_filename: "fullchain.pem"
site_dir: "/usr/share/nginx/html/{{ server_hostname }}"
