---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  {{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
stringData:
  db_password: {{ .Values.secret.data.db.password }}
