---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service_mysql.name }}
  {{- if .Values.namespace.enabled }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
spec:
  ports:
  - port: {{ .Values.service_mysql.port }}
  selector:
    app: {{ .Values.statefulset_mysql.name }}
  clusterIP: None
