---
- name: Install PHP, MariaDB, Nginx and Wordpress
  hosts: nodes
  gather_facts: true
  become: true

  vars_files:
    - vars/main.yaml

  pre_tasks:
    - name: PRE | Print vars
      debug:
        msg: "Server hostname: {{ server_hostname }}"

  roles:
    - role: mariadb
    - role: wordpress
    - role: crt
      delegate_to: localhost
      run_once: true
    - role: nginx
    - role: php

  post_tasks:
    - name: BLOCK | Check web site
      block:
        - name: HTTP | Check web site from control server | TLS
          uri:
            url: "https://{{ ansible_host }}:{{ nginx_port_tls }}"
            return_content: true
            validate_certs: false
          connection: local
          register: http_tls_check
          failed_when: http_tls_check.status != 200
          retries: 6
          delay: 2

        - name: HTTP | Check web site from control server | No TLS
          uri:
            url: "http://{{ ansible_host }}:{{ nginx_port_no_tls }}"
            return_content: true
            validate_certs: false
          connection: local
          register: http_not_tls_check
          failed_when: http_not_tls_check.status != 200
          retries: 6
          delay: 2
