---
- name: Install 'mariadb-server'
  yum:
    name: mariadb-server
    state: present

- name: Install 'MySQL-python' packages
  yum:
    name: MySQL-python
    state: latest

- name: Ensure 'mariadb' service is started and enabled
  service:
    name: mariadb
    state: started
    enabled: true

- name: Create "{{ db_name }}" database
  mysql_db:
    name: "{{ db_name }}"
    login_port: "{{ db_port }}"
    state: present

- name: >
    Create database user "{{ db_user }}" with password
    and grant it privilegies in "{{ db_name }}"
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL,GRANT"
    state: present
  no_log: true
