---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-env
  namespace: tensor
data:
  # can connect also by simple 'mysql' service name
  DB_HOST: mysql-0.mysql.tensor.svc.cluster.local
  DB_USER: root
  DB_DATABASE: my_db
