---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: python-app
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
      labels:
        name: python-app
    spec:
      containers:
      - image: python-app
        name: python-app
        imagePullPolicy: Never
        ports:
        - containerPort: 9080
          protocol: TCP
