---
- name: Collect facts about system services
  service_facts:
  register: services_state

- name: FIREWALLD | Enable ports
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    state: enabled
    immediate: true
  loop:
    - "{{ nginx_port_no_tls }}"
    - "{{ nginx_port_tls }}"
  when: ansible_facts.services["firewalld.service"].state in ["active", "running"]

- name: YUM | Setup Nginx repos
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    owner: root
    group: root
    mode: 0600

- name: YUM | Install Nginx
  yum:
    name: nginx
    update_cache: true
    state: present

- name: SSL | Ensure compute crt dir exists
  file:
    path: "{{ crt_compute_dir }}"
    state: directory
    owner: nginx
    group: nginx
    mode: 0600

- name: SSL | Copy crt and key from controller to compute
  copy:
    src: "{{ crt_controller_dir }}/{{ item }}"
    dest: "{{ crt_compute_dir }}/{{ item }}"
    owner: nginx
    group: nginx
    mode: 0600
  loop:
    - "{{ privatekey_filename }}"
    - "{{ crt_filename }}"

- name: NGINX | Copy nginx.conf
  copy:
    src: files/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: nginx
    group: nginx
    mode: 0600

- name: NGINX | Remove default config
  file:
    state: absent
    path: /etc/nginx/conf.d/default.conf

- name: NGINX | Copy host config
  template:
    src: templates/site.conf.j2
    dest: "/etc/nginx/conf.d/{{ server_hostname }}.conf"
    owner: nginx
    group: nginx
    mode: 0600

- name: Add nginx user to wordpress group
  ansible.builtin.user:
    name: nginx
    groups: wordpress
    append: true

- name: SYSTEMD | Ensure Nginx is enabled and started
  service:
    name: nginx
    state: started
    enabled: true

- name: Trigger nginx restart
  debug:
    msg: Trigger nginx restart
  notify: SYSTEMD | Restart Nginx
  changed_when: true
